[book]
title = "Handbook bee.software"
authors = ["Les membres de bee.software"]
description = "Le handbook bee.software couvre nos ententes de fonctionnement."
multilingual = false
src = "src"

[build]
build-dir = "build"
create-missing = true
preprocess = ["links", "index"]
